version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "emcek"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "emcek"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "emcek"
