api_ver: 3.6.3
autostart: false
check_bios: true
check_ver: true
color_mode: system
completer_items: 20
current_plane: A-10C
dcs: C:/Program Files/Eagle Dynamics/DCS World
dcsbios: C:/Users/UNKNOWN/Saved Games/DCS/Scripts/DCS-BIOS
debug_font_size: 10
device: G13
f16_ded_font: true
font_color_l: 32
font_color_m: 22
font_color_s: 18
font_mono_l: 16
font_mono_m: 11
font_mono_s: 9
font_name: consola.ttf
git_bios: true
git_bios_ref: main
gkeys_area: 2
gkeys_float: false
gui_debug: false
save_lcd: false
show_gui: true
toolbar_area: 4
toolbar_style: 0
verbose: false
