site_name: DCSpy

nav:
  - Home: 'index.md'
  - Development:
      - 'Contributing': 'CONTRIBUTING.md'
  - About:
    - 'License': 'LICENSE.md'
    - 'Secuirity': 'SECURITY.md'
    - 'Chnagelog': 'CHANGELOG.md'

theme:
  name: readthedocs
#  name: mkdocs

plugins:
  - search
  - plantuml-colocator  # ![Alt Text](my-diagram.puml)
  - mkdocstrings
