site_name: DCSpy
site_url: https://dcspy.readthedocs.io/
site_description: Software for integrating DCS Planes with Logitech keyboards (with and without LCD), mice and headphones.
repo_url: https://github.com/emcek/dcspy
copyright: Copyright &copy; 2019-2025 Michał Plichta

theme:
  name: material
  logo: dcspy.svg
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - media: '(prefers-color-scheme)'
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to system preference

nav:
  - Home: 'index.md'
  - Documentation:
      - Installation: 'install.md'
      - Upgrade: 'upgrade.md'
      - Usage: 'usage.md'
      - Planes and Helos: 'planes.md'
      - Supported devices: 'devices.md'
      - DCS-BIOS Live: 'bios_live.md'
      - Windows Defender: 'defender.md'
  - Information:
      - FAQ: 'faq.md'
      - Report issue: 'issue.md'
      - About: 'about.md'
      - Credits: 'credits.md'
  - API reference: reference/

plugins:
  - search
  - plantuml-colocator  # ![Alt Text](my-diagram.puml)
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          paths: [ src ]
          options:
            docstring_section_style: table
            docstring_style: sphinx
            filters: [ "!^_" ]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/emcek
  - icon: fontawesome/brands/discord
    link: https://discord.gg/SP5Yjx3
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/dcspy/
