[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dcspy"
version = "1.6.1"
description = "Integrating DCS (Digital Combat Simulator) planes with Logitech G13/G15/G510/G19 LCD"
readme = "README.md"
requires-python = ">=3.7"
authors = [{name = "Michal Plichta"}]
maintainers = [{name = "Michal Plichta"}]
keywords = ["logitech", "logitech-sdk", "logitech-keyboards", "logitech-gaming", "logitech-gaming-keyboard", "dcs-world", "dcs", "g13", "g15", "g510", "g19"]
license = {file = "LICENSE.md"}
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Environment :: Console',
    'Environment :: Win32 (MS Windows)',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: Microsoft :: Windows :: Windows 10',
    'Topic :: Games/Entertainment',
    'Topic :: Games/Entertainment :: Simulation',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'Topic :: System :: Hardware',
    'Topic :: Utilities'
]
dependencies = [
    "packaging",
    "Pillow",
    "psutil",
    "PyYAML",
    "requests",
    "typing-extensions; python_version < '3.8'",
]

[project.optional-dependencies]
test = ["pytest"]

[project.urls]
repository = "https://github.com/emcek/dcspy"

[project.scripts]
dcspy = "dcspy.dcspy:run"

[tool.setuptools]
platforms = ['win32', 'nt', 'Windows']
package-data = {"dcspy" = ['resources/dcspy.ico', 'resources/config.yaml']}
include-package-data = True

[tool.setuptools.packages.find]
where = ["dcspy"]
include = ["my_package*"]
exclude = ["tests*"]