@startuml
hide empty members

package dcsbios {
    class ProtocolParser {
        + state : str
        + sync_byte_count : int
        + address : int
        + count : int
        + data : int
        + write_callbacks : Set[Callable]
        + frame_sync_callbacks : Set[Callable]
        + process_byte(byte: int)
    }

    class StringBuffer {
        + buffer : bytearray
        + callbacks: Set[Callable]
        + __init__(parser, address, max_length, callback)
        + set_char(index, char)
        + on_dcsbios_write(address, data)
    }

    class IntegerBuffer {
        + callbacks: Set[Callable]
        + __init__(parser, address, mask, shift_by, callback)
        + on_dcsbios_write(address, data)
    }
}

package logitech {
    LogitechKeyboard <|-- KeyboardMono
    LogitechKeyboard <|-- KeyboardColor
}

class LogitechKeyboard {
    + parser : ProtocolParser
    + plane : Aircraft
    + plane_name = '' : str
    + plane_detected = False : bool
    + already_pressed = False : bool
    + buttons : Tuple[int]
    + lcd : LcdInfo
    + dislay(message : List[str]) -> List[str]
    # {abstract} _prepare_image() -> Image
    + detecting_plane()
    + load_new_plane(value : str)
    + check_buttons() -> int
    + button_handle(sock : socket)
    + clear()
    + text(List[str])
}

class KeyboardMono {
    + buttons : Tuple[int]
    # _prepare_image() -> Image
}

class KeyboardColor {
    + buttons : Tuple[int]
    # _prepare_image() -> Image
}


package aircrafts {
  Aircraft <|-- FA18Chornet
  Aircraft <|-- F16C50
  Aircraft <|-- Ka50
  Aircraft <|-- A10C
  A10C <|-- A10C2
  Aircraft <|-- F14B
  Aircraft <|-- AV8BNA
  class BIOS_VALUE
}

class Aircraft {
    + bios_data : Dict[str, BIOS_VALUE]
    + cycle_buttons : Dict[str, Iterator[int]]
    + lcd : LcdInfo
    # _debug_img : Iterator[int]
    + __init__(lcd_type: LcdInfo)
    + button_request(button: int, request: str) -> str
    + update_display(image : Image)
    + prepare_image() -> Image
    + set_bios(selector: str, value: str)
    + get_bios(selector: str) -> Union[str, int]
    + get_next_value_for_button(btn_name: str) -> int
    + {abstract} draw_for_lcd_type_1(img: Image)
    + {abstract} draw_for_lcd_type_2(img: Image)
}

LogitechKeyboard *- Aircraft
LogitechKeyboard *- LcdInfo
LogitechKeyboard *--- ProtocolParser
Aircraft *-- LcdInfo
Aircraft *-- StringBuffer
Aircraft *-- IntegerBuffer

class BIOS_VALUE <<(T,orange)>> {
    + class : str
    + args: Dict[str, int]
    + value: Union[int, str]
    + max_value: int
    - total=False
}

class LcdInfo <<(D,orchid)>> {
    + height : int
    + width : int
    + type : int
    + fg : Union[int, Sequence[int]]
    + bg : Union[int, Sequence[int]]
    + mode: str
    + font_s: ImageFont.FreeTypeFont
    + font_l: ImageFont.FreeTypeFont
}
@enduml