@startuml
hide empty members
package logitech {
    class LogitechDevice{
        + parser : ProtocolParser
        + plane : BasicAircraft
        + plane_name = '' : str
        + bios_name = '' : str
        + socket: socket
        + plane_detected = False : bool
        + lcdbutton_pressed = False : bool
        + gkey: Sequence[Gkey]
        + buttons: Sequence[LcdButton]
        + lcd : LcdInfo
        + model: KeyboardModel
        + vert_space = 0 : int
        + __init__(parser: ProtocolParser)
        + display(message : List[str]) -> List[str]
        + detecting_plane()
        + load_new_plane(value : str)
        + check_buttons() -> LcdButton
        + button_handle()
        + key_sdk: GkeySdkManager
        + lcd_sdk: LcdSdkManager
        + gkey_callback_handler(key: int, mode: int, key_down: int)
        + clear()
        + text(List[str])
        + skip_lcd: bool = False
        # _prepare_image() -> Image
        # _send_request(button: Union[LcdButton, Gkey], Optional[int])
    }
    class Headphone{
    }
    class Keyboard{
    }
    class Mouse{
    }
    class LcdKeyboard {
        + lcd : LcdInfo
        + model: KeyboardModel
        + vert_space = 0 : int
        + lcd_sdk: LcdSdkManager
        + __init__(parser: ProtocolParser)
    }
    class G13 {
        + gkey: Sequence[Gkey]
        + buttons: Sequence[LcdButton]
        + vert_space = 10 : int
    }
    class G510 {
        + gkey: Sequence[Gkey]
        + buttons: Sequence[LcdButton]
        + vert_space = 10 : int
    }
    class G15v1 {
        + gkey: Sequence[Gkey]
        + buttons: Sequence[LcdButton]
        + vert_space = 10 : int
    }
    class G15v2 {
        + gkey: Sequence[Gkey]
        + buttons: Sequence[LcdButton]
        + vert_space = 10 : int
    }
    class G19 {
        + gkey: Sequence[Gkey]
        + buttons: Sequence[LcdButton]
        + vert_space = 40 : int
    }

    LogitechDevice <|-- LcdKeyboard
    LogitechDevice <|-- Keyboard
    LogitechDevice <|-- Mouse
    LogitechDevice <|-- Headphone

    LcdKeyboard <|-- G13
    LcdKeyboard <|-- G510
    LcdKeyboard <|-- G15v1
    LcdKeyboard <|-- G15v2
    LcdKeyboard <|-- G19

    Keyboard <|-- G710
    Keyboard <|-- G110
    Keyboard <|-- G103
    Keyboard <|-- G105
    Keyboard <|-- G11

    Headphone <|-- G35
    Headphone <|-- G930

    Mouse <|-- G600
    Mouse <|-- G300
    Mouse <|-- G400
    Mouse <|-- G700
    Mouse <|-- G9
    Mouse <|-- MX518
    Mouse <|-- G402
    Mouse <|-- G502
    Mouse <|-- G602

}
@enduml