autostart: false
check_ver: false
dcs: C:\Program Files\Eagle Dynamics\DCS World OpenBeta
dcsbios: D:\Users\mplic\Saved Games\DCS.openbeta\Scripts\DCS-BIOS
f16_ded_font: true
font_color_l: 32
font_color_s: 22
font_color_xs: 18
font_mono_l: 16
font_mono_s: 11
font_mono_xs: 9
font_name: consola.ttf
keyboard: G13
show_gui: true
theme_color: dark-blue
theme_mode: light
verbose: true
