name: CodSpeed

on:
  push:
    branches:
      - "master"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Python environment"
        uses: ./.github/actions/setup-python

      - name: "Install MS Fonts"
        run: |
          curl -O https://lexics.github.io/assets/downloads/fonts/clearTypeFonts/consola.ttf
          sudo mkdir -p /usr/share/fonts/truetype
          sudo mv consola.ttf /usr/share/fonts/truetype
          fc-cache -f

      - name: "Run benchmarks"
        uses: CodSpeedHQ/action@v3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: python -m pytest -v --img_precision 0 --codspeed
