name: Check License

on: workflow_call

jobs:
  license_check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Check License"
        id: license_check_report
        uses: pilosus/action-pip-license-checker@v2
        with:
          requirements: 'requirements.txt'
          fail: 'Copyleft'

      - name: "Print report"
        if: ${{ always() }}
        run: echo "${{ steps.license_check_report.outputs.report }}"
