name: Check License

on: workflow_call

jobs:
  license_check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install uv and set the Python"
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true
          activate-environment: true

      - name: "Install the project and test dependencies"
        run: uv sync --no-extra test --no-extra docs --no-group dev

      - name: "Get explicit and transitive dependencies"
        run: |
          uv pip freeze > requirements-all.txt

      - name: "Check License"
        id: license_check_report
        uses: pilosus/action-pip-license-checker@v2
        with:
          requirements: 'requirements-all.txt'
          fail: 'StrongCopyleft,Other'
          totals: true
          headers: true
          exclude: '(?i)^(pyside6|shiboken6).*'

      - name: "Print report"
        if: ${{ always() }}
        run: echo "${{ steps.license_check_report.outputs.report }}"
