name: Check License

on: workflow_call

jobs:
  license_check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install requirements"
        run: |
          python -m pip install -U pip
          python -m pip install -U -r requirements.txt

      - name: "Get explicit and transitive dependencies"
        run: |
          pip freeze > requirements-all.txt

      - name: "Check License"
        id: license_check_report
        uses: pilosus/action-pip-license-checker@v2
        with:
          requirements: 'requirements-all.txt'
          fail: 'Copyleft'
#          exclude: '(?i)^(pyside6|shiboken6|docutils|certifi*).*'

      - name: "Print report"
        if: ${{ always() }}
        run: echo "${{ steps.license_check_report.outputs.report }}"
