name: Python CI

on: [push]

jobs:
  style:
    name: style ${{ matrix.os }} (py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.os }} ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -Ur requirements_test.txt
      - name: Check PyCodeStyle
        run: |
          pycodestyle --statistics --count dcspy
      - name: Check PyDocStyle
        run: |
          pydocstyle --count dcspy
      - name: Check PyLint
        run: |
          pylint dcspy || echo $(($? % 4))
      - name: Check flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=6 --ignore=E501 --max-line-length=160 --statistics
      - name: Check mypy
        run: |
          mypy --ignore-missing-imports --html-report mypyhtml dcspy
      - name: Upload mypy results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: mypy-${{ matrix.os }}-py${{ matrix.python-version }}
          path: |
            mypyhtml/*
          retention-days: 4
      - name: Check MANIFEST
        run: |
          check-manifest -q || echo $(($? -1))
  test:
    name: test ${{ matrix.os }} (py${{ matrix.python-version }})
    needs: style
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        exclude:
          - os: windows-latest
            python-version: '3.6'
          - os: windows-latest
            python-version: '3.7'
          - os: ubuntu-latest
            python-version: '3.10'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.os }} ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install MS Fonts
        if: ${{ contains( matrix.os, 'ubuntu') }}
        run: |
          curl -O https://lexics.github.io/assets/downloads/fonts/clearTypeFonts/consola.ttf
          sudo mkdir -p /usr/share/fonts/truetype
          sudo mv consola.ttf /usr/share/fonts/truetype
          fc-cache -f -v
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -Ur requirements_test.txt
      - name: Test with pytest
        run: |
          python -m pytest
      - name: Upload pytest test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: pytest-${{ matrix.os }}-${{ matrix.python-version }}
          path: |
            dcspy.log
          retention-days: 5
      - name: Check pip-audit
        run: |
          pip-audit -r requirements.txt --progress-spinner off
  coverage:
    name: cov ${{ matrix.os }} (py${{ matrix.python-version }})
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.os }} ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install MS Fonts
        if: ${{ contains( matrix.os, 'ubuntu') }}
        run: |
          curl -O https://lexics.github.io/assets/downloads/fonts/clearTypeFonts/consola.ttf
          sudo mkdir -p /usr/share/fonts/truetype
          sudo mv consola.ttf /usr/share/fonts/truetype
          fc-cache -f
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -Ur requirements_test.txt
      - name: Test with pytest
        run: |
          python -m pytest --cov=dcspy --cov-report=xml --cov-report=html --cov-report=term
      - name: Upload pytest results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-${{ matrix.os }}-py${{ matrix.python-version }}
          path: |
            htmlcov/*
            coverage.xml
            dcspy.log
          retention-days: 4
      - name: Run codacy-coverage
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          python-codacy-coverage -r coverage.xml
      - name: Test Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NAME: github
        run: |
          coveralls