name: Python CI

on: [push]

jobs:
  style:
    uses: ./.github/workflows/style.yml

  test:
    needs: [style]
    uses: ./.github/workflows/test.yml

  coverage:
    needs: [style]
    uses: ./.github/workflows/coverage.yml
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      COVERALLS_SERVICE_NAME: github
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
