name: Python CI

on: [push]

jobs:
  style:
    uses: ./.github/workflows/style.yml

  test:
    needs: [style]
    uses: ./.github/workflows/test.yml

  coverage:
    needs: [style]
    uses: ./.github/workflows/coverage.yml
