# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ github_actions, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        exclude:
          - os: windows-latest
            python-version: 3.6
          - os: windows-latest
            python-version: 3.7

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.os }} ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pytest-cov six coveralls pycodestyle pydocstyle pytest-mccabe pytest-random pylint coverage codacy-coverage mypy
          pip install -Ur requirements.txt
      - name: Check PyCodeStyle
        run: |
          pycodestyle --statistics --count dcspy
      - name: Check PyDocStyle
        run: |
          pydocstyle --count dcspy
      - name: Check mypy
        run: |
          mypy --ignore-missing-imports dcspy || echo $(($? - 1))
      - name: Check PyLint
        run: |
          pylint dcspy || echo $(($? % 4))
      - name: Test McCabe
        run: |
          pytest dcspy --mccabe
      - name: Test with pytest
        run: |
          python -m pytest -v --random --cov=dcspy --cov-report=xml --cov-report=html
          ls -la
          coverage run --source=dcspy -m pytest -v --random
          coverage xml
          ls -la
      - name: Upload pytest test results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: htmlcov/*
        if: ${{ always() }}
