name: Python CI

on: [push]

jobs:
  style:
    uses: ./.github/workflows/style.yml

  test:
    needs: [style]
    uses: ./.github/workflows/test.yml

  coverage:
    needs: [style]
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set up Python environment"
        uses: ./.github/actions/setup-python

      - name: "Install MS Fonts"
        run: |
          curl -O https://lexics.github.io/assets/downloads/fonts/clearTypeFonts/consola.ttf
          sudo mkdir -p /usr/share/fonts/truetype
          sudo mv consola.ttf /usr/share/fonts/truetype
          fc-cache -f

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -Ur requirements_test.txt

      - name: "Test with pytest"
        run: |
          python -m pytest -q --disable-warnings --cov=dcspy --cov-report=xml --cov-report=html --cov-report=term-missing -m "not dcsbios"

      - name: "Upload pytest results"
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-${{ matrix.os }}-py${{ matrix.python-version }}
          path: |
            covhtml/*
            coverage.xml
          retention-days: 4

      - name: "Run codacy-coverage"
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          python-codacy-coverage -r coverage.xml

      - name: "Test Coveralls"
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_SERVICE_NAME: github
        run: |
           coveralls
