name: Tox

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11.0-rc.2']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install MS Fonts
      run: |
        curl -O https://lexics.github.io/assets/downloads/fonts/clearTypeFonts/consola.ttf
        sudo mkdir -p /usr/share/fonts/truetype
        sudo mv consola.ttf /usr/share/fonts/truetype
        fc-cache -f -v
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
