name: test Download

on:
  push:
    branches: ["download-new-ver"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set up Python environment"
        uses: ./.github/actions/setup-python

      - name: "Build dcspy"
        uses: ./.github/actions/build-app

      - name: "Upload dcspy binaries"
        uses: actions/upload-artifact@v3
        with:
          name: dcspy_binaries
          path: dist/
